BADGES_SEED: list[dict[str, str | bool]] = [
    # Progress
    {"id": "first_step", "name": "Premier Pas", "description": "Complete ta premiere salle", "icon_key": "boot", "category": "progress", "secret": False},
    {"id": "zone1_clear", "name": "Stack Settler", "description": "Toutes les salles de Stack Village", "icon_key": "house", "category": "progress", "secret": False},
    {"id": "zone2_clear", "name": "Logic Knight", "description": "Toutes les salles de Logic Labyrinth", "icon_key": "sword", "category": "progress", "secret": False},
    {"id": "zone3_clear", "name": "Function Forger", "description": "Toutes les salles de Function Factory", "icon_key": "gear", "category": "progress", "secret": False},
    {"id": "zone4_clear", "name": "Data Defender", "description": "Toutes les salles de Data Fortress", "icon_key": "shield", "category": "progress", "secret": False},
    {"id": "zone5_clear", "name": "Pointer Paladin", "description": "Toutes les salles de Pointer Abyss", "icon_key": "arrow", "category": "progress", "secret": False},
    {"id": "zone6_clear", "name": "String Sorcerer", "description": "Toutes les salles de String Caverns", "icon_key": "wand", "category": "progress", "secret": False},
    {"id": "zone7_clear", "name": "Heap Hero", "description": "Toutes les salles de Heap Wastes", "icon_key": "crown", "category": "progress", "secret": False},
    {"id": "zone8_clear", "name": "File Phantom", "description": "Toutes les salles de File Sanctum", "icon_key": "scroll", "category": "progress", "secret": False},
    {"id": "dungeon_master", "name": "Dungeon Master", "description": "Complete les 8 zones — tu maitrises le C !", "icon_key": "trophy", "category": "progress", "secret": False},
    {"id": "halfway", "name": "Mi-Parcours", "description": "60 salles completees — tu es a mi-chemin !", "icon_key": "milestone", "category": "progress", "secret": False},
    # Mini-boss badges
    {"id": "zone1_miniboss_1", "name": "Garde des Variables vaincu", "description": "Mini-boss 1 de Stack Village battu", "icon_key": "mini_shield", "category": "progress", "secret": False},
    {"id": "zone1_miniboss_2", "name": "Sentinelle Printf vaincue", "description": "Mini-boss 2 de Stack Village battu", "icon_key": "mini_shield", "category": "progress", "secret": False},
    {"id": "zone2_miniboss_1", "name": "Piege Conditionnel dejoue", "description": "Mini-boss 1 de Logic Labyrinth battu", "icon_key": "mini_shield", "category": "progress", "secret": False},
    {"id": "zone2_miniboss_2", "name": "Boucle Infernale brisee", "description": "Mini-boss 2 de Logic Labyrinth battu", "icon_key": "mini_shield", "category": "progress", "secret": False},
    {"id": "zone3_miniboss_1", "name": "Gardien des Prototypes vaincu", "description": "Mini-boss 1 de Function Factory battu", "icon_key": "mini_shield", "category": "progress", "secret": False},
    {"id": "zone3_miniboss_2", "name": "Spectre du Scope dissipe", "description": "Mini-boss 2 de Function Factory battu", "icon_key": "mini_shield", "category": "progress", "secret": False},
    {"id": "zone4_miniboss_1", "name": "Sentinelle des Tableaux vaincue", "description": "Mini-boss 1 de Data Fortress battu", "icon_key": "mini_shield", "category": "progress", "secret": False},
    {"id": "zone4_miniboss_2", "name": "Titan du Tri terrasse", "description": "Mini-boss 2 de Data Fortress battu", "icon_key": "mini_shield", "category": "progress", "secret": False},
    {"id": "zone5_miniboss_1", "name": "Fantome de l'Adresse exorcise", "description": "Mini-boss 1 de Pointer Abyss battu", "icon_key": "mini_shield", "category": "progress", "secret": False},
    {"id": "zone5_miniboss_2", "name": "Arithmeticien des Pointeurs vaincu", "description": "Mini-boss 2 de Pointer Abyss battu", "icon_key": "mini_shield", "category": "progress", "secret": False},
    {"id": "zone6_miniboss_1", "name": "Gardien du Null vaincu", "description": "Mini-boss 1 de String Caverns battu", "icon_key": "mini_shield", "category": "progress", "secret": False},
    {"id": "zone6_miniboss_2", "name": "Demon des Buffers vaincu", "description": "Mini-boss 2 de String Caverns battu", "icon_key": "mini_shield", "category": "progress", "secret": False},
    {"id": "zone7_miniboss_1", "name": "Spectre du Malloc dissipe", "description": "Mini-boss 1 de Heap Wastes battu", "icon_key": "mini_shield", "category": "progress", "secret": False},
    {"id": "zone7_miniboss_2", "name": "Gardien du Free vaincu", "description": "Mini-boss 2 de Heap Wastes battu", "icon_key": "mini_shield", "category": "progress", "secret": False},
    {"id": "zone8_miniboss_1", "name": "Gardien des Modes vaincu", "description": "Mini-boss 1 de File Sanctum battu", "icon_key": "mini_shield", "category": "progress", "secret": False},
    {"id": "zone8_miniboss_2", "name": "Spectre Binaire dissipe", "description": "Mini-boss 2 de File Sanctum battu", "icon_key": "mini_shield", "category": "progress", "secret": False},
    # Skill
    {"id": "flawless_room", "name": "Sans Faute", "description": "Complete une salle sans erreur", "icon_key": "star", "category": "skill", "secret": False},
    {"id": "boss_first_try", "name": "One Shot", "description": "Bats un boss du premier coup", "icon_key": "lightning", "category": "skill", "secret": False},
    {"id": "speedrun_room", "name": "Speed Daemon", "description": "Complete une salle en moins de 20 secondes", "icon_key": "clock", "category": "skill", "secret": True},
    {"id": "bug_hunter", "name": "Bug Hunter", "description": "Trouve le bug 10 fois de suite", "icon_key": "bug", "category": "skill", "secret": False},
    {"id": "perfectionist", "name": "Perfectionniste", "description": "Toutes les salles completees sans erreur", "icon_key": "diamond", "category": "skill", "secret": True},
    # Streak / Combo
    {"id": "combo_5", "name": "Combo x5", "description": "Atteins un combo x5", "icon_key": "fire_1", "category": "streak", "secret": False},
    {"id": "combo_10", "name": "Combo x10", "description": "Atteins un combo x10", "icon_key": "fire_2", "category": "streak", "secret": False},
    {"id": "combo_20", "name": "Inarretable", "description": "Combo x20 — tu es une machine", "icon_key": "fire_3", "category": "streak", "secret": True},
    {"id": "daily_3", "name": "3 jours de suite", "description": "Daily challenge 3 jours consecutifs", "icon_key": "calendar_3", "category": "streak", "secret": False},
    {"id": "daily_7", "name": "Week Warrior", "description": "Daily challenge 7 jours consecutifs", "icon_key": "calendar_7", "category": "streak", "secret": False},
    # Explorer
    {"id": "pointer_master", "name": "Pointer Master", "description": "100% sur les challenges pointeurs", "icon_key": "arrow", "category": "explorer", "secret": False},
    {"id": "no_hints", "name": "No Hints Needed", "description": "Complete une zone sans hint", "icon_key": "eye", "category": "explorer", "secret": True},
]
