"""
All challenge content for C:\\DUNGEON.
8 zones x 6 rooms (5 normal + 1 boss) = 48 rooms total.
Each room has one challenge. Challenge types rotate to keep it fresh.
"""

CHALLENGES: dict[str, dict] = {

    # ===== ZONE 1: STACK VILLAGE =====
    # Concepts: variables, types, printf, scanf, compilation

    "z01_r01": {
        "challenge_id": "z01_r01",
        "zone": 1, "room": 1, "is_boss": False,
        "challenge_type": "match_types",
        "title": "L'Armurerie des Types",
        "concept_tags": ["types", "variables"],
        "difficulty": 1,
        "question_prompt": "Chaque valeur doit aller dans le bon casier. Associe chaque valeur à son type C !",
        "hint": "En C : int = entier, float = décimal court, double = décimal long, char = un seul caractère entre ''",
        "explanation": "En C, chaque variable a un type précis. int pour les entiers, float/double pour les décimaux, char pour un caractère.",
        "payload": {
            "values": [
                {"id": "v1", "display": "42"},
                {"id": "v2", "display": "'Z'"},
                {"id": "v3", "display": "3.14"},
                {"id": "v4", "display": "2.718281828"},
            ],
            "types": [
                {"id": "t1", "label": "int"},
                {"id": "t2", "label": "float"},
                {"id": "t3", "label": "double"},
                {"id": "t4", "label": "char"},
            ],
            "correct_answer": {"v1": "t1", "v2": "t4", "v3": "t2", "v4": "t3"},
        },
    },

    "z01_r02": {
        "challenge_id": "z01_r02",
        "zone": 1, "room": 2, "is_boss": False,
        "challenge_type": "fill_blank",
        "title": "La Formule Manquante",
        "concept_tags": ["variables", "declaration", "printf"],
        "difficulty": 1,
        "question_prompt": "Complete la déclaration de variable pour afficher l'âge de l'étudiant.",
        "hint": "Pour déclarer un entier en C, on écrit : type nom = valeur;",
        "explanation": "int est le type pour les nombres entiers. La syntaxe est : int nom = valeur;",
        "payload": {
            "code_before": "",
            "code_segments": [
                {"type": "code", "text": "___"},
                {"type": "code", "text": " age = 20;"},
                {"type": "newline"},
                {"type": "code", "text": 'printf("Age: %d", age);'},
            ],
            "options": ["int", "void", "return", "char"],
            "correct_answer": "int",
        },
    },

    "z01_r03": {
        "challenge_id": "z01_r03",
        "zone": 1, "room": 3, "is_boss": False,
        "challenge_type": "trace_value",
        "title": "La Machine à Calculer",
        "concept_tags": ["variables", "arithmetic", "operators"],
        "difficulty": 1,
        "question_prompt": "Suis l'exécution du code. Quelle est la valeur finale de 'score' ?",
        "hint": "Lis le code ligne par ligne, comme le fait le CPU. Chaque = modifie la valeur.",
        "explanation": "score = 10, puis +5 = 15, puis *2 = 30. Chaque opération modifie la variable.",
        "payload": {
            "code_lines": [
                {"line": 1, "text": "int score = 10;"},
                {"line": 2, "text": "score = score + 5;"},
                {"line": 3, "text": "score = score * 2;"},
            ],
            "animation_steps": [
                {"after_line": 1, "variable": "score", "value": 10},
                {"after_line": 2, "variable": "score", "value": 15},
            ],
            "question": "Après la ligne 3 (score = score * 2), score = ?",
            "options": [15, 20, 30, 25],
            "correct_answer": 30,
        },
    },

    "z01_r04": {
        "challenge_id": "z01_r04",
        "zone": 1, "room": 4, "is_boss": False,
        "challenge_type": "find_bug",
        "title": "Le Code Maudit",
        "concept_tags": ["syntax", "semicolon", "declaration"],
        "difficulty": 1,
        "question_prompt": "Une ligne contient un bug de syntaxe. Clique dessus !",
        "hint": "En C, chaque instruction se termine par un point-virgule ;",
        "explanation": "La ligne 2 manque un point-virgule. C'est l'une des erreurs de syntaxe les plus communes en C.",
        "payload": {
            "code_lines": [
                {"line": 1, "text": "int main() {", "is_bug": False},
                {"line": 2, "text": "  int x = 5", "is_bug": True},
                {"line": 3, "text": '  printf("%d\\n", x);', "is_bug": False},
                {"line": 4, "text": "  return 0;", "is_bug": False},
                {"line": 5, "text": "}", "is_bug": False},
            ],
            "correct_answer": 2,
            "bug_explanation": "Oubli du point-virgule ; en fin de déclaration",
        },
    },

    "z01_r05": {
        "challenge_id": "z01_r05",
        "zone": 1, "room": 5, "is_boss": False,
        "challenge_type": "sort_order",
        "title": "Les Étapes de la Compilation",
        "concept_tags": ["compilation", "workflow"],
        "difficulty": 1,
        "question_prompt": "Remet dans l'ordre les étapes de création d'un programme C.",
        "hint": "On écrit d'abord, puis on compile (traduit en machine), puis on exécute.",
        "explanation": "Le flux est : Écrire le .c → Compiler avec gcc → Obtenir un exécutable → Lancer le programme.",
        "payload": {
            "cards": [
                {"id": "c1", "text": "Écrire le code dans fichier.c"},
                {"id": "c2", "text": "Compiler avec gcc"},
                {"id": "c3", "text": "Obtenir l'exécutable"},
                {"id": "c4", "text": "Lancer le programme"},
            ],
            "display_order": ["c3", "c1", "c4", "c2"],
            "correct_answer": ["c1", "c2", "c3", "c4"],
        },
    },

    "z01_r06": {  # BOSS
        "challenge_id": "z01_r06",
        "zone": 1, "room": 6, "is_boss": True,
        "challenge_type": "memory_map",
        "title": "BOSS : Le Golem des Types",
        "concept_tags": ["variables", "types", "memory"],
        "difficulty": 2,
        "question_prompt": "Le Golem garde la mémoire. Chaque variable occupe un emplacement. Clique sur l'adresse qui contient la variable 'b'.",
        "hint": "Les variables sont rangées en mémoire dans l'ordre de déclaration. a est en premier.",
        "explanation": "En C, les variables locales sont allouées sur la stack dans l'ordre. int a occupe 0x100, int b occupe 0x104 (4 bytes après).",
        "payload": {
            "grid_size": {"rows": 2, "cols": 3},
            "code_context": ["int a = 10;", "int b = 20;", "int c = 30;"],
            "question": "Quelle adresse contient la variable 'b' ?",
            "interaction_mode": "click_cell",
            "correct_answer": "0x104",
            "visual_state": {
                "0x100": {"label": "a", "value": "10", "highlight": "var"},
                "0x104": {"label": "b", "value": "20", "highlight": "var"},
                "0x108": {"label": "c", "value": "30", "highlight": "var"},
                "0x10C": {"label": "???", "value": "...", "highlight": "empty"},
                "0x110": {"label": "???", "value": "...", "highlight": "empty"},
                "0x114": {"label": "???", "value": "...", "highlight": "empty"},
            },
            "addresses": [
                {"address": "0x100", "row": 0, "col": 0},
                {"address": "0x104", "row": 0, "col": 1},
                {"address": "0x108", "row": 0, "col": 2},
                {"address": "0x10C", "row": 1, "col": 0},
                {"address": "0x110", "row": 1, "col": 1},
                {"address": "0x114", "row": 1, "col": 2},
            ],
        },
    },

    # ===== ZONE 2: LOGIC LABYRINTH =====
    # Concepts: if/else, boolean, loops, break/continue

    "z02_r01": {
        "challenge_id": "z02_r01",
        "zone": 2, "room": 1, "is_boss": False,
        "challenge_type": "fill_blank",
        "title": "La Porte Conditionnelle",
        "concept_tags": ["conditions", "if-else"],
        "difficulty": 1,
        "question_prompt": "La porte s'ouvre si x > 10. Quel mot-clé déclenche le cas contraire ?",
        "hint": "if gère le cas vrai, ___ gère le cas faux.",
        "explanation": "else est le compagnon de if. Il s'exécute quand la condition de if est fausse.",
        "payload": {
            "code_segments": [
                {"type": "code", "text": "if (x > 10) {"},
                {"type": "newline"},
                {"type": "code", "text": '  printf("Porte ouverte");'},
                {"type": "newline"},
                {"type": "code", "text": "} ___"},
                {"type": "code", "text": " {"},
                {"type": "newline"},
                {"type": "code", "text": '  printf("Porte fermée");'},
                {"type": "newline"},
                {"type": "code", "text": "}"},
            ],
            "options": ["else", "elif", "otherwise", "then"],
            "correct_answer": "else",
        },
    },

    "z02_r02": {
        "challenge_id": "z02_r02",
        "zone": 2, "room": 2, "is_boss": False,
        "challenge_type": "trace_value",
        "title": "Le Labyrinthe Logique",
        "concept_tags": ["boolean", "logical-operators", "conditions"],
        "difficulty": 2,
        "question_prompt": "Avec a=3 et b=7, quelle valeur affiche ce code ?",
        "hint": "&& signifie ET (les deux conditions doivent être vraies). || signifie OU (au moins une vraie).",
        "explanation": "a<5 est VRAI et b>5 est VRAI. Les deux sont vrais → && donne VRAI → on entre dans le if → résultat = 1.",
        "payload": {
            "code_lines": [
                {"line": 1, "text": "int a = 3, b = 7;"},
                {"line": 2, "text": "int res = 0;"},
                {"line": 3, "text": "if (a < 5 && b > 5) {"},
                {"line": 4, "text": "  res = 1;"},
                {"line": 5, "text": "} else {"},
                {"line": 6, "text": "  res = 2;"},
                {"line": 7, "text": "}"},
            ],
            "animation_steps": [
                {"after_line": 1, "variable": "a", "value": 3},
                {"after_line": 1, "variable": "b", "value": 7},
                {"after_line": 2, "variable": "res", "value": 0},
            ],
            "question": "a<5 est VRAI. b>5 est VRAI. Quelle valeur prend res ?",
            "options": [0, 1, 2, 3],
            "correct_answer": 1,
        },
    },

    "z02_r03": {
        "challenge_id": "z02_r03",
        "zone": 2, "room": 3, "is_boss": False,
        "challenge_type": "find_bug",
        "title": "La Boucle Brisée",
        "concept_tags": ["loops", "for", "infinite-loop"],
        "difficulty": 2,
        "question_prompt": "Cette boucle ne se termine jamais ! Trouve la ligne responsable.",
        "hint": "Une boucle for a 3 parties : init ; condition ; incrément. Laquelle est fausse ici ?",
        "explanation": "La ligne 2 utilise i-- au lieu de i++. i commence à 0 et décroît indéfiniment → boucle infinie !",
        "payload": {
            "code_lines": [
                {"line": 1, "text": "int i;", "is_bug": False},
                {"line": 2, "text": "for (i = 0; i < 5; i--) {", "is_bug": True},
                {"line": 3, "text": '  printf("%d\\n", i);', "is_bug": False},
                {"line": 4, "text": "}", "is_bug": False},
            ],
            "correct_answer": 2,
            "bug_explanation": "i-- décrémente i au lieu de l'incrémenter → boucle infinie",
        },
    },

    "z02_r04": {
        "challenge_id": "z02_r04",
        "zone": 2, "room": 4, "is_boss": False,
        "challenge_type": "trace_value",
        "title": "Compter les Survivants",
        "concept_tags": ["loops", "while", "counters"],
        "difficulty": 2,
        "question_prompt": "Combien de fois printf est-il appelé dans cette boucle while ?",
        "hint": "Trace la valeur de n à chaque tour : combien de fois la condition est-elle vraie ?",
        "explanation": "n double à chaque tour : 1→2→4→8→16. La condition n<10 est vraie pour n=1,2,4,8 → printf est appelé 4 fois.",
        "payload": {
            "code_lines": [
                {"line": 1, "text": "int n = 1;"},
                {"line": 2, "text": "while (n < 10) {"},
                {"line": 3, "text": '  printf("%d\\n", n);'},
                {"line": 4, "text": "  n = n * 2;"},
                {"line": 5, "text": "}"},
            ],
            "animation_steps": [
                {"after_line": 1, "variable": "n", "value": 1},
                {"after_line": 3, "variable": "printf_call", "value": "n=1"},
                {"after_line": 4, "variable": "n", "value": 2},
                {"after_line": 3, "variable": "printf_call", "value": "n=2"},
                {"after_line": 4, "variable": "n", "value": 4},
                {"after_line": 3, "variable": "printf_call", "value": "n=4"},
                {"after_line": 4, "variable": "n", "value": 8},
            ],
            "question": "La boucle continue-t-elle avec n=8 ? Combien de fois printf est appelé en tout ?",
            "options": [2, 3, 4, 5],
            "correct_answer": 4,
        },
    },

    "z02_r05": {
        "challenge_id": "z02_r05",
        "zone": 2, "room": 5, "is_boss": False,
        "challenge_type": "sort_order",
        "title": "Le Chemin du if/else if/else",
        "concept_tags": ["conditions", "if-else", "chained-conditions"],
        "difficulty": 2,
        "question_prompt": "Remets les blocs dans l'ordre logique pour classer une note.",
        "hint": "On teste d'abord la condition la plus restrictive, puis on élargit.",
        "explanation": "On vérifie dans l'ordre : >= 90 (A), >= 70 (B), >= 50 (C), sinon (F). L'ordre est crucial.",
        "payload": {
            "cards": [
                {"id": "c1", "text": 'if (note >= 90) { printf("A"); }'},
                {"id": "c2", "text": 'else if (note >= 70) { printf("B"); }'},
                {"id": "c3", "text": 'else if (note >= 50) { printf("C"); }'},
                {"id": "c4", "text": 'else { printf("F"); }'},
            ],
            "display_order": ["c4", "c2", "c1", "c3"],
            "correct_answer": ["c1", "c2", "c3", "c4"],
        },
    },

    "z02_r06": {  # BOSS
        "challenge_id": "z02_r06",
        "zone": 2, "room": 6, "is_boss": True,
        "challenge_type": "trace_value",
        "title": "BOSS : Le Golem Infinite Loop",
        "concept_tags": ["loops", "for", "do-while", "break"],
        "difficulty": 3,
        "question_prompt": "Le Golem utilise do-while. Quelle est la valeur de count après exécution ?",
        "hint": "do-while s'exécute AU MOINS UNE FOIS avant de tester la condition.",
        "explanation": "do-while : exécute d'abord, vérifie ensuite. count commence à 0, +1 à chaque tour. La condition count<3 stoppe à count=3.",
        "payload": {
            "code_lines": [
                {"line": 1, "text": "int count = 0;"},
                {"line": 2, "text": "do {"},
                {"line": 3, "text": "  count++;"},
                {"line": 4, "text": "} while (count < 3);"},
            ],
            "animation_steps": [
                {"after_line": 1, "variable": "count", "value": 0},
                {"after_line": 3, "variable": "count", "value": 1},
                {"after_line": 3, "variable": "count", "value": 2},
            ],
            "question": "do-while s'exécute encore si count<3. Valeur finale de count ?",
            "options": [2, 3, 4, 0],
            "correct_answer": 3,
        },
    },

    # ===== ZONE 3: FUNCTION FACTORY =====
    # Concepts: functions, parameters, return, prototypes, multi-files

    "z03_r01": {
        "challenge_id": "z03_r01",
        "zone": 3, "room": 1, "is_boss": False,
        "challenge_type": "fill_blank",
        "title": "L'Atelier des Fonctions",
        "concept_tags": ["functions", "return-type"],
        "difficulty": 2,
        "question_prompt": "Cette fonction additionne deux entiers et retourne le résultat. Quel est son type de retour ?",
        "hint": "Le type de retour précède le nom de la fonction. Si elle retourne un entier...",
        "explanation": "Une fonction qui retourne un entier doit être déclarée avec int. void = ne retourne rien.",
        "payload": {
            "code_segments": [
                {"type": "code", "text": "___"},
                {"type": "code", "text": " additionner(int a, int b) {"},
                {"type": "newline"},
                {"type": "code", "text": "  return a + b;"},
                {"type": "newline"},
                {"type": "code", "text": "}"},
            ],
            "options": ["int", "void", "float", "return"],
            "correct_answer": "int",
        },
    },

    "z03_r02": {
        "challenge_id": "z03_r02",
        "zone": 3, "room": 2, "is_boss": False,
        "challenge_type": "trace_value",
        "title": "L'Appel de la Fonction",
        "concept_tags": ["functions", "parameters", "return"],
        "difficulty": 2,
        "question_prompt": "Trace l'appel de fonction. Quelle valeur est stockée dans 'resultat' ?",
        "hint": "Les paramètres sont des copies des valeurs passées. Trace a et b dans la fonction.",
        "explanation": "doubler(7) → a=7, retourne 7*2=14. Ce 14 est stocké dans resultat.",
        "payload": {
            "code_lines": [
                {"line": 1, "text": "int doubler(int a) {"},
                {"line": 2, "text": "  return a * 2;"},
                {"line": 3, "text": "}"},
                {"line": 4, "text": "int resultat = doubler(7);"},
            ],
            "animation_steps": [
                {"after_line": 1, "variable": "a (dans doubler)", "value": 7},
                {"after_line": 2, "variable": "retour", "value": 14},
            ],
            "question": "doubler(7) retourne 14. Quelle est la valeur de resultat après la ligne 4 ?",
            "options": [7, 14, 49, 2],
            "correct_answer": 14,
        },
    },

    "z03_r03": {
        "challenge_id": "z03_r03",
        "zone": 3, "room": 3, "is_boss": False,
        "challenge_type": "find_bug",
        "title": "Le Prototype Fantôme",
        "concept_tags": ["functions", "prototype", "declaration"],
        "difficulty": 2,
        "question_prompt": "Ce code compile mais donne un résultat bizarre. Trouve le bug !",
        "hint": "Le compilateur C lit de haut en bas. Si une fonction est utilisée avant sa définition...",
        "explanation": "La fonction carre est utilisée ligne 3 avant d'être définie ligne 6. Il manque un prototype (déclaration) avant main.",
        "payload": {
            "code_lines": [
                {"line": 1, "text": "int main() {", "is_bug": False},
                {"line": 2, "text": "  int n = 5;", "is_bug": False},
                {"line": 3, "text": "  int r = carre(n);", "is_bug": True},
                {"line": 4, "text": "  return 0;", "is_bug": False},
                {"line": 5, "text": "}", "is_bug": False},
                {"line": 6, "text": "int carre(int x) { return x*x; }", "is_bug": False},
            ],
            "correct_answer": 3,
            "bug_explanation": "carre() est utilisée avant d'être déclarée. Ajouter int carre(int x); avant main().",
        },
    },

    "z03_r04": {
        "challenge_id": "z03_r04",
        "zone": 3, "room": 4, "is_boss": False,
        "challenge_type": "match_types",
        "title": "Les Signatures de Fonctions",
        "concept_tags": ["functions", "return-type", "parameters"],
        "difficulty": 2,
        "question_prompt": "Associe chaque fonction à son type de retour correct.",
        "hint": "Le type de retour dépend de ce que retourne la fonction avec 'return'.",
        "explanation": "sqrt retourne un double, strlen retourne un entier non signé, getchar retourne un int (code ASCII), printf retourne void.",
        "payload": {
            "values": [
                {"id": "v1", "display": "sqrt(double)  → retourne une racine"},
                {"id": "v2", "display": "strlen(str)   → retourne une longueur"},
                {"id": "v3", "display": "afficher()    → ne retourne rien"},
                {"id": "v4", "display": "moyenne(a,b)  → retourne un décimal"},
            ],
            "types": [
                {"id": "t1", "label": "double"},
                {"id": "t2", "label": "int"},
                {"id": "t3", "label": "void"},
                {"id": "t4", "label": "float"},
            ],
            "correct_answer": {"v1": "t1", "v2": "t2", "v3": "t3", "v4": "t4"},
        },
    },

    "z03_r05": {
        "challenge_id": "z03_r05",
        "zone": 3, "room": 5, "is_boss": False,
        "challenge_type": "sort_order",
        "title": "Architecture Multi-Fichiers",
        "concept_tags": ["multi-files", "header", "compilation"],
        "difficulty": 2,
        "question_prompt": "Remets dans l'ordre les éléments d'un projet multi-fichiers.",
        "hint": "Les .h déclarent, les .c définissent, le linker assemble.",
        "explanation": "Organisation type : déclarations dans .h → implémentations dans .c → inclusion du .h dans main → compilation → link.",
        "payload": {
            "cards": [
                {"id": "c1", "text": "Écrire les prototypes dans fonctions.h"},
                {"id": "c2", "text": "Implémenter les fonctions dans fonctions.c"},
                {"id": "c3", "text": '#include "fonctions.h" dans main.c'},
                {"id": "c4", "text": "Compiler main.c et fonctions.c"},
                {"id": "c5", "text": "Linker → exécutable final"},
            ],
            "display_order": ["c4", "c3", "c5", "c1", "c2"],
            "correct_answer": ["c1", "c2", "c3", "c4", "c5"],
        },
    },

    "z03_r06": {  # BOSS
        "challenge_id": "z03_r06",
        "zone": 3, "room": 6, "is_boss": True,
        "challenge_type": "trace_value",
        "title": "BOSS : L'Usine Récursive",
        "concept_tags": ["functions", "recursion"],
        "difficulty": 3,
        "question_prompt": "La fonction mystère est récursive. Quelle valeur retourne-t-elle pour n=4 ?",
        "hint": "Trace les appels : f(4) appelle f(3) appelle f(2) appelle f(1). f(1) = 1.",
        "explanation": "C'est la factorielle ! f(4)=4*f(3)=4*3*f(2)=4*3*2*f(1)=4*3*2*1=24.",
        "payload": {
            "code_lines": [
                {"line": 1, "text": "int f(int n) {"},
                {"line": 2, "text": "  if (n <= 1) return 1;"},
                {"line": 3, "text": "  return n * f(n - 1);"},
                {"line": 4, "text": "}"},
                {"line": 5, "text": "int res = f(4);"},
            ],
            "animation_steps": [
                {"after_line": 5, "variable": "f(4) appelle...", "value": "f(3)"},
                {"after_line": 3, "variable": "f(3) appelle...", "value": "f(2)"},
                {"after_line": 3, "variable": "f(2) appelle...", "value": "f(1)"},
                {"after_line": 2, "variable": "f(1) retourne", "value": 1},
                {"after_line": 3, "variable": "f(2) retourne", "value": 2},
                {"after_line": 3, "variable": "f(3) retourne", "value": 6},
                {"after_line": 3, "variable": "f(4) retourne", "value": 24},
            ],
            "question": "Valeur de res = f(4) ?",
            "options": [4, 12, 24, 16],
            "correct_answer": 24,
        },
    },

    # ===== ZONE 4: DATA FORTRESS =====
    # Concepts: arrays, structs, typedef

    "z04_r01": {
        "challenge_id": "z04_r01",
        "zone": 4, "room": 1, "is_boss": False,
        "challenge_type": "fill_blank",
        "title": "Le Coffre à Tableaux",
        "concept_tags": ["arrays", "indexing"],
        "difficulty": 2,
        "question_prompt": "Les tableaux commencent à l'index 0. Quel index accède au 3ème élément ?",
        "hint": "Premier élément = index 0, deuxième = index 1, troisième = ?",
        "explanation": "En C, les indices démarrent à 0. Le 3ème élément est à l'index 2.",
        "payload": {
            "code_segments": [
                {"type": "code", "text": "int scores[5] = {10, 20, 30, 40, 50};"},
                {"type": "newline"},
                {"type": "code", "text": "printf(\"%d\", scores["},
                {"type": "code", "text": "___"},
                {"type": "code", "text": "]);  // affiche 30"},
            ],
            "options": ["2", "3", "1", "0"],
            "correct_answer": "2",
        },
    },

    "z04_r02": {
        "challenge_id": "z04_r02",
        "zone": 4, "room": 2, "is_boss": False,
        "challenge_type": "trace_value",
        "title": "La Somme du Tableau",
        "concept_tags": ["arrays", "loops", "iteration"],
        "difficulty": 2,
        "question_prompt": "Quelle valeur est stockée dans 'somme' après la boucle ?",
        "hint": "Parcours le tableau avec i=0,1,2,3,4 et additionne chaque élément.",
        "explanation": "somme = 0+1+2+3+4 = 10.",
        "payload": {
            "code_lines": [
                {"line": 1, "text": "int t[5] = {0,1,2,3,4};"},
                {"line": 2, "text": "int somme = 0, i;"},
                {"line": 3, "text": "for (i=0; i<5; i++) {"},
                {"line": 4, "text": "  somme += t[i];"},
                {"line": 5, "text": "}"},
            ],
            "animation_steps": [
                {"after_line": 2, "variable": "somme", "value": 0},
                {"after_line": 4, "variable": "somme", "value": 1},
                {"after_line": 4, "variable": "somme", "value": 3},
                {"after_line": 4, "variable": "somme", "value": 6},
                {"after_line": 4, "variable": "somme", "value": 10},
            ],
            "question": "Valeur finale de somme ?",
            "options": [10, 15, 4, 5],
            "correct_answer": 10,
        },
    },

    "z04_r03": {
        "challenge_id": "z04_r03",
        "zone": 4, "room": 3, "is_boss": False,
        "challenge_type": "find_bug",
        "title": "Le Débordement de Tableau",
        "concept_tags": ["arrays", "out-of-bounds", "buffer-overflow"],
        "difficulty": 3,
        "question_prompt": "Ce code provoque un accès hors limite ! Quelle ligne est coupable ?",
        "hint": "Un tableau de taille N a des indices de 0 à N-1.",
        "explanation": "Ligne 3 : t[5] est hors du tableau qui va de t[0] à t[4]. Accès à l'index 5 → undefined behavior !",
        "payload": {
            "code_lines": [
                {"line": 1, "text": "int t[5] = {1,2,3,4,5};", "is_bug": False},
                {"line": 2, "text": "int i;", "is_bug": False},
                {"line": 3, "text": "for (i=0; i<=5; i++) {", "is_bug": True},
                {"line": 4, "text": '  printf("%d ", t[i]);', "is_bug": False},
                {"line": 5, "text": "}", "is_bug": False},
            ],
            "correct_answer": 3,
            "bug_explanation": "i<=5 dépasse le tableau. Utiliser i<5 (indices 0 à 4).",
        },
    },

    "z04_r04": {
        "challenge_id": "z04_r04",
        "zone": 4, "room": 4, "is_boss": False,
        "challenge_type": "match_types",
        "title": "L'Architecte des Structs",
        "concept_tags": ["structs", "typedef"],
        "difficulty": 2,
        "question_prompt": "Associe chaque champ d'une structure Etudiant à son type approprié.",
        "hint": "Choisis le type le plus adapté à chaque donnée représentée.",
        "explanation": "age = int, note = float (décimal), nom = char[] (tableau de caractères), id_promo = int.",
        "payload": {
            "values": [
                {"id": "v1", "display": "age  (ex: 20)"},
                {"id": "v2", "display": "note (ex: 14.5)"},
                {"id": "v3", "display": "nom  (ex: 'Alice')"},
                {"id": "v4", "display": "present (oui/non)"},
            ],
            "types": [
                {"id": "t1", "label": "int"},
                {"id": "t2", "label": "float"},
                {"id": "t3", "label": "char[]"},
                {"id": "t4", "label": "int (0/1)"},
            ],
            "correct_answer": {"v1": "t1", "v2": "t2", "v3": "t3", "v4": "t4"},
        },
    },

    "z04_r05": {
        "challenge_id": "z04_r05",
        "zone": 4, "room": 5, "is_boss": False,
        "challenge_type": "fill_blank",
        "title": "Accéder aux Membres",
        "concept_tags": ["structs", "dot-notation"],
        "difficulty": 2,
        "question_prompt": "Comment accède-t-on au champ 'age' de la structure 'etu' ?",
        "hint": "Pour accéder à un membre d'une variable struct, on utilise le point '.' : variable.membre",
        "explanation": "La notation point permet d'accéder aux membres d'une struct. etu.age lit le champ age de etu.",
        "payload": {
            "code_segments": [
                {"type": "code", "text": "typedef struct { int age; } Etudiant;"},
                {"type": "newline"},
                {"type": "code", "text": "Etudiant etu;"},
                {"type": "newline"},
                {"type": "code", "text": "etu"},
                {"type": "code", "text": "___"},
                {"type": "code", "text": "age = 21;"},
            ],
            "options": [".", "->", "::", "→"],
            "correct_answer": ".",
        },
    },

    "z04_r06": {  # BOSS
        "challenge_id": "z04_r06",
        "zone": 4, "room": 6, "is_boss": True,
        "challenge_type": "sort_order",
        "title": "BOSS : La Forteresse des Données",
        "concept_tags": ["structs", "arrays", "iteration"],
        "difficulty": 3,
        "question_prompt": "Remets dans l'ordre le code qui calcule la meilleure note d'un tableau de structs Etudiant.",
        "hint": "D'abord déclarer, initialiser max, puis boucler, puis comparer.",
        "explanation": "L'algorithme cherche le max : init max au premier élément, puis comparer chaque suivant.",
        "payload": {
            "cards": [
                {"id": "c1", "text": "Etudiant promo[3] = { {\"Alice\",18}, {\"Bob\",15}, {\"Clara\",20} };"},
                {"id": "c2", "text": "float max = promo[0].note;"},
                {"id": "c3", "text": "for (int i=1; i<3; i++) {"},
                {"id": "c4", "text": "  if (promo[i].note > max) max = promo[i].note;"},
                {"id": "c5", "text": "}"},
            ],
            "display_order": ["c3", "c5", "c1", "c4", "c2"],
            "correct_answer": ["c1", "c2", "c3", "c4", "c5"],
        },
    },

    # ===== ZONE 5: POINTER ABYSS =====
    # Concepts: pointers, address-of, dereference, pass-by-reference

    "z05_r01": {
        "challenge_id": "z05_r01",
        "zone": 5, "room": 1, "is_boss": False,
        "challenge_type": "fill_blank",
        "title": "L'Adresse Secrète",
        "concept_tags": ["pointers", "address-of"],
        "difficulty": 2,
        "question_prompt": "Quel opérateur obtient l'adresse mémoire d'une variable ?",
        "hint": "En C, deux opérateurs : & prend l'adresse, * déréférence (accède à la valeur pointée).",
        "explanation": "& est l'opérateur 'adresse de'. &x donne l'adresse mémoire de x. * est l'opérateur de déréférencement.",
        "payload": {
            "code_segments": [
                {"type": "code", "text": "int x = 42;"},
                {"type": "newline"},
                {"type": "code", "text": "int *ptr = "},
                {"type": "code", "text": "___"},
                {"type": "code", "text": "x;  // ptr pointe vers x"},
            ],
            "options": ["&", "*", "->", "#"],
            "correct_answer": "&",
        },
    },

    "z05_r02": {
        "challenge_id": "z05_r02",
        "zone": 5, "room": 2, "is_boss": False,
        "challenge_type": "memory_map",
        "title": "La Carte de la Mémoire",
        "concept_tags": ["pointers", "memory", "dereference"],
        "difficulty": 3,
        "question_prompt": "Après ce code, quelle adresse contient ptr ? Clique sur la bonne case.",
        "hint": "ptr = &y signifie ptr stocke l'adresse de y.",
        "explanation": "ptr = &y → ptr stocke l'adresse de y, soit 0x204. *ptr vaut donc 99.",
        "payload": {
            "grid_size": {"rows": 2, "cols": 3},
            "code_context": ["int x = 50;", "int y = 99;", "int *ptr = &y;"],
            "question": "Quelle adresse est stockée dans ptr ?",
            "interaction_mode": "click_cell",
            "correct_answer": "0x204",
            "visual_state": {
                "0x200": {"label": "x", "value": "50", "highlight": "var"},
                "0x204": {"label": "y", "value": "99", "highlight": "var"},
                "0x208": {"label": "ptr", "value": "0x204", "highlight": "ptr"},
                "0x20C": {"label": "???", "value": "...", "highlight": "empty"},
                "0x210": {"label": "???", "value": "...", "highlight": "empty"},
                "0x214": {"label": "???", "value": "...", "highlight": "empty"},
            },
            "addresses": [
                {"address": "0x200", "row": 0, "col": 0},
                {"address": "0x204", "row": 0, "col": 1},
                {"address": "0x208", "row": 0, "col": 2},
                {"address": "0x20C", "row": 1, "col": 0},
                {"address": "0x210", "row": 1, "col": 1},
                {"address": "0x214", "row": 1, "col": 2},
            ],
        },
    },

    "z05_r03": {
        "challenge_id": "z05_r03",
        "zone": 5, "room": 3, "is_boss": False,
        "challenge_type": "trace_value",
        "title": "Le Déréférencement",
        "concept_tags": ["pointers", "dereference", "modify-through-pointer"],
        "difficulty": 3,
        "question_prompt": "Après *ptr = 100, quelle est la valeur de x ?",
        "hint": "*ptr = ... modifie la valeur à l'adresse pointée par ptr. Si ptr = &x, alors *ptr modifie x.",
        "explanation": "ptr pointe sur x. *ptr = 100 écrit 100 à l'adresse de x. Donc x devient 100.",
        "payload": {
            "code_lines": [
                {"line": 1, "text": "int x = 42;"},
                {"line": 2, "text": "int *ptr = &x;"},
                {"line": 3, "text": "*ptr = 100;"},
            ],
            "animation_steps": [
                {"after_line": 1, "variable": "x", "value": 42},
                {"after_line": 2, "variable": "ptr", "value": "&x"},
                {"after_line": 3, "variable": "x (via *ptr)", "value": 100},
            ],
            "question": "Valeur de x après *ptr = 100 ?",
            "options": [42, 100, 0, "indéfinie"],
            "correct_answer": 100,
        },
    },

    "z05_r04": {
        "challenge_id": "z05_r04",
        "zone": 5, "room": 4, "is_boss": False,
        "challenge_type": "find_bug",
        "title": "Le Pointeur NULL",
        "concept_tags": ["pointers", "null-pointer", "segfault"],
        "difficulty": 3,
        "question_prompt": "Ce code cause un Segmentation Fault (crash). Trouve la ligne coupable !",
        "hint": "Un pointeur NULL ne pointe nulle part. Le déréférencer = CRASH.",
        "explanation": "Ligne 3 : ptr est NULL (non initialisé à une adresse valide). *ptr tente d'accéder à l'adresse 0 → Segfault !",
        "payload": {
            "code_lines": [
                {"line": 1, "text": "int *ptr = NULL;", "is_bug": False},
                {"line": 2, "text": "int x = 5;", "is_bug": False},
                {"line": 3, "text": "*ptr = x;", "is_bug": True},
                {"line": 4, "text": 'printf("%d", *ptr);', "is_bug": False},
            ],
            "correct_answer": 3,
            "bug_explanation": "ptr est NULL → déréférencer NULL cause un Segmentation Fault.",
        },
    },

    "z05_r05": {
        "challenge_id": "z05_r05",
        "zone": 5, "room": 5, "is_boss": False,
        "challenge_type": "fill_blank",
        "title": "Passage par Adresse",
        "concept_tags": ["pointers", "pass-by-reference", "functions"],
        "difficulty": 3,
        "question_prompt": "Pour modifier 'x' depuis une fonction, on passe son adresse. Comment appeller tripler(&x) ?",
        "hint": "Le paramètre est un pointeur int*. Dans la fonction, pour modifier la valeur, on utilise *.",
        "explanation": "*n *= 3 déréférence n pour modifier la valeur originale. Sans *, on ne modifierait qu'une copie.",
        "payload": {
            "code_segments": [
                {"type": "code", "text": "void tripler(int *n) {"},
                {"type": "newline"},
                {"type": "code", "text": "  "},
                {"type": "code", "text": "___"},
                {"type": "code", "text": "n *= 3;"},
                {"type": "newline"},
                {"type": "code", "text": "}"},
            ],
            "options": ["*", "&", "**", ""],
            "correct_answer": "*",
        },
    },

    "z05_r06": {  # BOSS
        "challenge_id": "z05_r06",
        "zone": 5, "room": 6, "is_boss": True,
        "challenge_type": "memory_map",
        "title": "BOSS : Le Dragon Segfault",
        "concept_tags": ["pointers", "arrays", "pointer-arithmetic"],
        "difficulty": 3,
        "question_prompt": "ptr pointe sur t[0]. Après ptr++, sur quoi pointe ptr ? Clique sur la bonne case.",
        "hint": "L'arithmétique des pointeurs : ptr++ avance au prochain élément (selon le type, ici int = +4 bytes).",
        "explanation": "ptr++ avance d'un int (4 bytes). ptr était sur t[0] à 0x300, donc ptr++ → 0x304 = t[1].",
        "payload": {
            "grid_size": {"rows": 2, "cols": 3},
            "code_context": ["int t[4] = {10, 20, 30, 40};", "int *ptr = t;  // = &t[0]", "ptr++;"],
            "question": "Après ptr++, sur quelle case pointe ptr ?",
            "interaction_mode": "click_cell",
            "correct_answer": "0x304",
            "visual_state": {
                "0x300": {"label": "t[0]", "value": "10", "highlight": "var"},
                "0x304": {"label": "t[1]", "value": "20", "highlight": "var"},
                "0x308": {"label": "t[2]", "value": "30", "highlight": "var"},
                "0x30C": {"label": "t[3]", "value": "40", "highlight": "var"},
                "0x310": {"label": "???", "value": "...", "highlight": "empty"},
                "0x314": {"label": "???", "value": "...", "highlight": "empty"},
            },
            "addresses": [
                {"address": "0x300", "row": 0, "col": 0},
                {"address": "0x304", "row": 0, "col": 1},
                {"address": "0x308", "row": 0, "col": 2},
                {"address": "0x30C", "row": 1, "col": 0},
                {"address": "0x310", "row": 1, "col": 1},
                {"address": "0x314", "row": 1, "col": 2},
            ],
        },
    },

    # ===== ZONE 6: STRING CAVERNS =====
    # Concepts: char arrays, string functions, random

    "z06_r01": {
        "challenge_id": "z06_r01",
        "zone": 6, "room": 1, "is_boss": False,
        "challenge_type": "fill_blank",
        "title": "La Chaîne Mystérieuse",
        "concept_tags": ["strings", "char-array", "null-terminator"],
        "difficulty": 2,
        "question_prompt": "Les chaînes C se terminent par un caractère spécial. Lequel ?",
        "hint": "C'est le caractère de valeur 0, noté '\\0' ou NULL character.",
        "explanation": "'\\0' est le null terminator. Toute chaîne C se termine par '\\0' pour indiquer la fin.",
        "payload": {
            "code_segments": [
                {"type": "code", "text": "char nom[6] = {'A','l','i','c','e',"},
                {"type": "code", "text": "___"},
                {"type": "code", "text": "};"},
                {"type": "newline"},
                {"type": "code", "text": "// 'Alice' + fin de chaîne"},
            ],
            "options": ["'\\0'", "'\\n'", "NULL", "0x00"],
            "correct_answer": "'\\0'",
        },
    },

    "z06_r02": {
        "challenge_id": "z06_r02",
        "zone": 6, "room": 2, "is_boss": False,
        "challenge_type": "match_types",
        "title": "L'Arsenal des Fonctions String",
        "concept_tags": ["strings", "string-functions", "stdlib"],
        "difficulty": 2,
        "question_prompt": "Associe chaque fonction string à ce qu'elle fait.",
        "hint": "str = string, len = length, cpy = copy, cat = concatenate, cmp = compare",
        "explanation": "strlen=longueur, strcpy=copier, strcat=concatener, strcmp=comparer. Ces fonctions sont dans <string.h>.",
        "payload": {
            "values": [
                {"id": "v1", "display": "strlen(s)"},
                {"id": "v2", "display": "strcpy(dst, src)"},
                {"id": "v3", "display": "strcat(s1, s2)"},
                {"id": "v4", "display": "strcmp(s1, s2)"},
            ],
            "types": [
                {"id": "t1", "label": "Retourne la longueur"},
                {"id": "t2", "label": "Copie src dans dst"},
                {"id": "t3", "label": "Concatène s2 à s1"},
                {"id": "t4", "label": "Compare deux chaînes"},
            ],
            "correct_answer": {"v1": "t1", "v2": "t2", "v3": "t3", "v4": "t4"},
        },
    },

    "z06_r03": {
        "challenge_id": "z06_r03",
        "zone": 6, "room": 3, "is_boss": False,
        "challenge_type": "trace_value",
        "title": "La Longueur du Mot",
        "concept_tags": ["strings", "strlen"],
        "difficulty": 2,
        "question_prompt": "Quelle valeur retourne strlen pour cette chaîne ?",
        "hint": "strlen compte les caractères SANS le '\\0' final.",
        "explanation": "'Bonjour' = 7 caractères (B,o,n,j,o,u,r). strlen retourne 7, sans compter le '\\0'.",
        "payload": {
            "code_lines": [
                {"line": 1, "text": 'char s[] = "Bonjour";'},
                {"line": 2, "text": "int len = strlen(s);"},
            ],
            "animation_steps": [
                {"after_line": 1, "variable": "s", "value": "B,o,n,j,o,u,r,\\0"},
                {"after_line": 2, "variable": "len", "value": 7},
            ],
            "question": "Valeur de len ?",
            "options": [6, 7, 8, 0],
            "correct_answer": 7,
        },
    },

    "z06_r04": {
        "challenge_id": "z06_r04",
        "zone": 6, "room": 4, "is_boss": False,
        "challenge_type": "find_bug",
        "title": "Le Générateur de Chaos",
        "concept_tags": ["random", "rand", "srand", "time"],
        "difficulty": 2,
        "question_prompt": "Ce code génère toujours la même séquence aléatoire. Trouve le bug !",
        "hint": "rand() a besoin d'une graine (seed) aléatoire. Que se passe-t-il si on ne l'initialise pas ?",
        "explanation": "Sans srand(time(NULL)), rand() utilise toujours la même graine → même séquence. Il faut appeler srand(time(NULL)) avant rand().",
        "payload": {
            "code_lines": [
                {"line": 1, "text": "#include <stdlib.h>", "is_bug": False},
                {"line": 2, "text": "#include <time.h>", "is_bug": False},
                {"line": 3, "text": "int main() {", "is_bug": False},
                {"line": 4, "text": "  // srand(time(NULL)); oublié !", "is_bug": True},
                {"line": 5, "text": "  int n = rand() % 10;", "is_bug": False},
                {"line": 6, "text": "  return 0;", "is_bug": False},
                {"line": 7, "text": "}", "is_bug": False},
            ],
            "correct_answer": 4,
            "bug_explanation": "Sans srand(time(NULL)), rand() retourne toujours la même séquence.",
        },
    },

    "z06_r05": {
        "challenge_id": "z06_r05",
        "zone": 6, "room": 5, "is_boss": False,
        "challenge_type": "sort_order",
        "title": "Inverser une Chaîne",
        "concept_tags": ["strings", "char-array", "algorithms"],
        "difficulty": 3,
        "question_prompt": "Remets dans l'ordre l'algorithme qui inverse une chaîne.",
        "hint": "Pour inverser : trouve la longueur, puis échange les caractères en partant des extrémités.",
        "explanation": "Algorithme : longueur → boucle d'échange (début/fin se rapprochant) → terminé.",
        "payload": {
            "cards": [
                {"id": "c1", "text": "int len = strlen(s);"},
                {"id": "c2", "text": "int i = 0, j = len - 1;"},
                {"id": "c3", "text": "while (i < j) {"},
                {"id": "c4", "text": "  char tmp = s[i]; s[i] = s[j]; s[j] = tmp;"},
                {"id": "c5", "text": "  i++; j--;"},
                {"id": "c6", "text": "}"},
            ],
            "display_order": ["c3", "c6", "c4", "c1", "c5", "c2"],
            "correct_answer": ["c1", "c2", "c3", "c4", "c5", "c6"],
        },
    },

    "z06_r06": {  # BOSS
        "challenge_id": "z06_r06",
        "zone": 6, "room": 6, "is_boss": True,
        "challenge_type": "trace_value",
        "title": "BOSS : L'Oracle des Chaînes",
        "concept_tags": ["strings", "char-array", "loops", "comparison"],
        "difficulty": 3,
        "question_prompt": "Ce code compte les voyelles dans 'ECE'. Quelle valeur retourne-t-il ?",
        "hint": "Parcours 'E','C','E'. Parmi eux, lesquels sont des voyelles (a,e,i,o,u) ?",
        "explanation": "'E' est voyelle, 'C' non, 'E' est voyelle. count = 2.",
        "payload": {
            "code_lines": [
                {"line": 1, "text": 'char s[] = "ECE";'},
                {"line": 2, "text": "int count = 0;"},
                {"line": 3, "text": "for (int i=0; s[i]!='\\0'; i++) {"},
                {"line": 4, "text": "  char c = s[i] | 32;  // lowercase"},
                {"line": 5, "text": "  if (c=='a'||c=='e'||c=='i'||c=='o'||c=='u')"},
                {"line": 6, "text": "    count++;"},
                {"line": 7, "text": "}"},
            ],
            "animation_steps": [
                {"after_line": 2, "variable": "count", "value": 0},
                {"after_line": 4, "variable": "c (i=0)", "value": "'e'"},
                {"after_line": 6, "variable": "count", "value": 1},
                {"after_line": 4, "variable": "c (i=1)", "value": "'c'"},
                {"after_line": 4, "variable": "c (i=2)", "value": "'e'"},
                {"after_line": 6, "variable": "count", "value": 2},
            ],
            "question": "Valeur finale de count ?",
            "options": [1, 2, 3, 0],
            "correct_answer": 2,
        },
    },

    # ===== ZONE 7: HEAP WASTES =====
    # Concepts: malloc, calloc, realloc, free, memory leaks

    "z07_r01": {
        "challenge_id": "z07_r01",
        "zone": 7, "room": 1, "is_boss": False,
        "challenge_type": "fill_blank",
        "title": "La Forge du Heap",
        "concept_tags": ["malloc", "dynamic-allocation"],
        "difficulty": 3,
        "question_prompt": "Alloue dynamiquement 5 entiers. Quelle fonction utiliser ?",
        "hint": "malloc(taille_en_bytes) alloue de la mémoire sur le tas (heap). sizeof(int) = 4 bytes.",
        "explanation": "malloc(5 * sizeof(int)) alloue 20 bytes pour 5 entiers. Retourne un void* à caster.",
        "payload": {
            "code_segments": [
                {"type": "code", "text": "int *t = (int*) "},
                {"type": "code", "text": "___"},
                {"type": "code", "text": "(5 * sizeof(int));"},
                {"type": "newline"},
                {"type": "code", "text": "// Vérifie si t != NULL"},
            ],
            "options": ["malloc", "alloc", "new", "calloc"],
            "correct_answer": "malloc",
        },
    },

    "z07_r02": {
        "challenge_id": "z07_r02",
        "zone": 7, "room": 2, "is_boss": False,
        "challenge_type": "find_bug",
        "title": "La Fuite de Mémoire",
        "concept_tags": ["malloc", "free", "memory-leak"],
        "difficulty": 3,
        "question_prompt": "Ce code a une memory leak ! Quelle ligne est responsable ?",
        "hint": "Toute mémoire allouée avec malloc DOIT être libérée avec free() avant la fin.",
        "explanation": "Ligne 5 : la fonction retourne sans appeler free(ptr). La mémoire allouée est perdue = memory leak.",
        "payload": {
            "code_lines": [
                {"line": 1, "text": "void processData() {", "is_bug": False},
                {"line": 2, "text": "  int *ptr = malloc(100 * sizeof(int));", "is_bug": False},
                {"line": 3, "text": "  if (!ptr) return;", "is_bug": False},
                {"line": 4, "text": "  // ... traitement ...", "is_bug": False},
                {"line": 5, "text": "  return;  // oubli de free !", "is_bug": True},
                {"line": 6, "text": "}", "is_bug": False},
            ],
            "correct_answer": 5,
            "bug_explanation": "Il manque free(ptr) avant le return. Chaque malloc doit avoir son free.",
        },
    },

    "z07_r03": {
        "challenge_id": "z07_r03",
        "zone": 7, "room": 3, "is_boss": False,
        "challenge_type": "sort_order",
        "title": "Le Rituel du malloc",
        "concept_tags": ["malloc", "free", "null-check"],
        "difficulty": 3,
        "question_prompt": "Remets dans l'ordre les étapes correctes pour utiliser malloc en sécurité.",
        "hint": "Toujours vérifier si malloc a réussi (retourne NULL si échec) avant d'utiliser la mémoire.",
        "explanation": "Bonne pratique : allouer → vérifier NULL → utiliser → libérer.",
        "payload": {
            "cards": [
                {"id": "c1", "text": "int *t = malloc(n * sizeof(int));"},
                {"id": "c2", "text": "if (t == NULL) { return -1; }"},
                {"id": "c3", "text": "// Utiliser t[0], t[1], ..."},
                {"id": "c4", "text": "free(t);"},
                {"id": "c5", "text": "t = NULL;  // Sécurité anti-dangling"},
            ],
            "display_order": ["c3", "c5", "c1", "c4", "c2"],
            "correct_answer": ["c1", "c2", "c3", "c4", "c5"],
        },
    },

    "z07_r04": {
        "challenge_id": "z07_r04",
        "zone": 7, "room": 4, "is_boss": False,
        "challenge_type": "trace_value",
        "title": "La Réallocation",
        "concept_tags": ["realloc", "dynamic-allocation"],
        "difficulty": 3,
        "question_prompt": "Après realloc, combien d'entiers peut-on stocker dans t ?",
        "hint": "realloc redimensionne un bloc existant. La nouvelle taille remplace l'ancienne.",
        "explanation": "t commence à 5 entiers, puis realloc(t, 10*sizeof(int)) l'agrandit à 10. On peut stocker 10 entiers.",
        "payload": {
            "code_lines": [
                {"line": 1, "text": "int *t = malloc(5 * sizeof(int));"},
                {"line": 2, "text": "// t peut contenir 5 ints"},
                {"line": 3, "text": "t = realloc(t, 10 * sizeof(int));"},
                {"line": 4, "text": "// t peut maintenant contenir ?"},
            ],
            "animation_steps": [
                {"after_line": 1, "variable": "capacité", "value": 5},
                {"after_line": 3, "variable": "capacité", "value": 10},
            ],
            "question": "Combien d'entiers après realloc ?",
            "options": [5, 10, 15, 50],
            "correct_answer": 10,
        },
    },

    "z07_r05": {
        "challenge_id": "z07_r05",
        "zone": 7, "room": 5, "is_boss": False,
        "challenge_type": "match_types",
        "title": "Les Alliés de l'Allocation",
        "concept_tags": ["malloc", "calloc", "realloc", "free"],
        "difficulty": 3,
        "question_prompt": "Associe chaque fonction à son rôle dans la gestion mémoire.",
        "hint": "calloc = cleared alloc (initialise à 0). realloc = re-alloue (change la taille).",
        "explanation": "malloc=allouer, calloc=allouer+initialiser à 0, realloc=redimensionner, free=libérer.",
        "payload": {
            "values": [
                {"id": "v1", "display": "malloc(size)"},
                {"id": "v2", "display": "calloc(n, size)"},
                {"id": "v3", "display": "realloc(ptr, size)"},
                {"id": "v4", "display": "free(ptr)"},
            ],
            "types": [
                {"id": "t1", "label": "Alloue (non initialisé)"},
                {"id": "t2", "label": "Alloue + init à zéro"},
                {"id": "t3", "label": "Redimensionne"},
                {"id": "t4", "label": "Libère la mémoire"},
            ],
            "correct_answer": {"v1": "t1", "v2": "t2", "v3": "t3", "v4": "t4"},
        },
    },

    "z07_r06": {  # BOSS
        "challenge_id": "z07_r06",
        "zone": 7, "room": 6, "is_boss": True,
        "challenge_type": "find_bug",
        "title": "BOSS : L'Hydre Memory Leak",
        "concept_tags": ["malloc", "free", "double-free", "dangling-pointer"],
        "difficulty": 3,
        "question_prompt": "Ce code a un double-free ! C'est pire qu'un leak. Quelle ligne crashe ?",
        "hint": "free() ne doit être appelé qu'UNE SEULE FOIS par pointeur. Appeler free() deux fois = undefined behavior.",
        "explanation": "Ligne 5 : free(ptr) est appelé une deuxième fois. Après le premier free, ptr est un dangling pointer. Double-free = crash ou corruption mémoire.",
        "payload": {
            "code_lines": [
                {"line": 1, "text": "int *ptr = malloc(sizeof(int));", "is_bug": False},
                {"line": 2, "text": "*ptr = 42;", "is_bug": False},
                {"line": 3, "text": "free(ptr);  // premier free OK", "is_bug": False},
                {"line": 4, "text": "ptr = NULL;  // bonne pratique", "is_bug": False},
                {"line": 5, "text": "free(ptr);  // double free !", "is_bug": True},
            ],
            "correct_answer": 5,
            "bug_explanation": "free() sur un pointeur déjà libéré (même si NULL ici, le pattern est dangereux). free(NULL) est en fait OK en C, mais free sur un ptr non-NULL déjà libéré = crash.",
        },
    },

    # ===== ZONE 8: FILE SANCTUM =====
    # Concepts: fopen, fclose, fprintf, fscanf, fgets, binary files

    "z08_r01": {
        "challenge_id": "z08_r01",
        "zone": 8, "room": 1, "is_boss": False,
        "challenge_type": "fill_blank",
        "title": "La Clé du Sanctuaire",
        "concept_tags": ["files", "fopen", "modes"],
        "difficulty": 2,
        "question_prompt": "Pour ouvrir un fichier en ÉCRITURE (en effaçant le contenu), quel mode utiliser ?",
        "hint": "Modes de fopen : 'r'=read, 'w'=write (efface), 'a'=append, 'r+'=read+write",
        "explanation": "'w' ouvre en écriture et efface le contenu existant. 'a' ouvre en écriture en fin de fichier.",
        "payload": {
            "code_segments": [
                {"type": "code", "text": 'FILE *f = fopen("data.txt", "'},
                {"type": "code", "text": "___"},
                {"type": "code", "text": '");'},
                {"type": "newline"},
                {"type": "code", "text": "// Écriture depuis le début"},
            ],
            "options": ["w", "r", "a", "x"],
            "correct_answer": "w",
        },
    },

    "z08_r02": {
        "challenge_id": "z08_r02",
        "zone": 8, "room": 2, "is_boss": False,
        "challenge_type": "sort_order",
        "title": "Le Rituel d'Écriture",
        "concept_tags": ["files", "fopen", "fprintf", "fclose"],
        "difficulty": 2,
        "question_prompt": "Remets dans l'ordre les étapes pour écrire dans un fichier.",
        "hint": "Toujours : ouvrir → vérifier → utiliser → fermer.",
        "explanation": "L'ordre correct : ouvrir avec fopen → vérifier que f != NULL → écrire avec fprintf → fermer avec fclose.",
        "payload": {
            "cards": [
                {"id": "c1", "text": 'FILE *f = fopen("score.txt", "w");'},
                {"id": "c2", "text": "if (f == NULL) return -1;"},
                {"id": "c3", "text": 'fprintf(f, "Score: %d\\n", score);'},
                {"id": "c4", "text": "fclose(f);"},
            ],
            "display_order": ["c3", "c1", "c4", "c2"],
            "correct_answer": ["c1", "c2", "c3", "c4"],
        },
    },

    "z08_r03": {
        "challenge_id": "z08_r03",
        "zone": 8, "room": 3, "is_boss": False,
        "challenge_type": "find_bug",
        "title": "Le Fichier Fantôme",
        "concept_tags": ["files", "fopen", "null-check"],
        "difficulty": 2,
        "question_prompt": "Ce code crashe si le fichier n'existe pas. Quelle ligne est en cause ?",
        "hint": "fopen retourne NULL si le fichier ne peut pas être ouvert. Il faut toujours vérifier !",
        "explanation": "Ligne 3 : on utilise f sans vérifier si fopen a réussi. Si f == NULL, fscanf crash.",
        "payload": {
            "code_lines": [
                {"line": 1, "text": 'FILE *f = fopen("config.txt", "r");', "is_bug": False},
                {"line": 2, "text": "int val;", "is_bug": False},
                {"line": 3, "text": 'fscanf(f, "%d", &val);  // pas de vérif !', "is_bug": True},
                {"line": 4, "text": "fclose(f);", "is_bug": False},
            ],
            "correct_answer": 3,
            "bug_explanation": "Si fopen échoue, f = NULL. Utiliser NULL avec fscanf = crash. Toujours if (f == NULL) avant.",
        },
    },

    "z08_r04": {
        "challenge_id": "z08_r04",
        "zone": 8, "room": 4, "is_boss": False,
        "challenge_type": "match_types",
        "title": "Les Gardiens des Fichiers",
        "concept_tags": ["files", "file-functions"],
        "difficulty": 2,
        "question_prompt": "Associe chaque fonction fichier à son action.",
        "hint": "f devant = file. fprintf = printf vers fichier. fscanf = scanf depuis fichier.",
        "explanation": "fopen=ouvrir, fclose=fermer, fprintf=écrire formaté, fscanf=lire formaté, fgets=lire une ligne.",
        "payload": {
            "values": [
                {"id": "v1", "display": "fopen(path, mode)"},
                {"id": "v2", "display": "fclose(f)"},
                {"id": "v3", "display": "fprintf(f, fmt, ...)"},
                {"id": "v4", "display": "fgets(buf, n, f)"},
            ],
            "types": [
                {"id": "t1", "label": "Ouvre un fichier"},
                {"id": "t2", "label": "Ferme un fichier"},
                {"id": "t3", "label": "Écrit formaté dans fichier"},
                {"id": "t4", "label": "Lit une ligne entière"},
            ],
            "correct_answer": {"v1": "t1", "v2": "t2", "v3": "t3", "v4": "t4"},
        },
    },

    "z08_r05": {
        "challenge_id": "z08_r05",
        "zone": 8, "room": 5, "is_boss": False,
        "challenge_type": "fill_blank",
        "title": "Le Mode Binaire",
        "concept_tags": ["files", "binary", "fwrite", "fread"],
        "difficulty": 3,
        "question_prompt": "Pour ouvrir un fichier en mode BINAIRE en lecture, quel mode passer à fopen ?",
        "hint": "On ajoute 'b' au mode texte. 'r' → 'rb', 'w' → 'wb'.",
        "explanation": "'rb' = read binary. Le 'b' indique qu'on lit en binaire (important sur Windows, transparent sur Linux).",
        "payload": {
            "code_segments": [
                {"type": "code", "text": 'FILE *f = fopen("data.bin", "'},
                {"type": "code", "text": "___"},
                {"type": "code", "text": '");'},
                {"type": "newline"},
                {"type": "code", "text": "// Lecture en mode binaire"},
            ],
            "options": ["rb", "br", "r", "bin"],
            "correct_answer": "rb",
        },
    },

    "z08_r06": {  # BOSS
        "challenge_id": "z08_r06",
        "zone": 8, "room": 6, "is_boss": True,
        "challenge_type": "sort_order",
        "title": "BOSS : Le Gardien du Sanctuaire",
        "concept_tags": ["files", "fwrite", "fread", "binary"],
        "difficulty": 3,
        "question_prompt": "Remets dans l'ordre pour sauvegarder et recharger une struct depuis un fichier binaire.",
        "hint": "Écrire avec fwrite(struct, taille, 1, f), lire avec fread. Toujours ouvrir/fermer correctement.",
        "explanation": "Le flux binaire : ouvrir en écriture → fwrite la struct → fermer → ouvrir en lecture → fread → fermer.",
        "payload": {
            "cards": [
                {"id": "c1", "text": 'FILE *fw = fopen("save.bin", "wb");'},
                {"id": "c2", "text": "fwrite(&player, sizeof(Player), 1, fw);"},
                {"id": "c3", "text": "fclose(fw);"},
                {"id": "c4", "text": 'FILE *fr = fopen("save.bin", "rb");'},
                {"id": "c5", "text": "fread(&player, sizeof(Player), 1, fr);"},
                {"id": "c6", "text": "fclose(fr);"},
            ],
            "display_order": ["c4", "c2", "c6", "c1", "c5", "c3"],
            "correct_answer": ["c1", "c2", "c3", "c4", "c5", "c6"],
        },
    },
}


# Zone metadata
ZONES = [
    {
        "zone_number": 1, "name": "Stack Village", "theme": "village",
        "emoji": "🏠", "boss_name": "Le Golem des Types",
        "description": "Variables, types, printf/scanf. Les fondations.",
    },
    {
        "zone_number": 2, "name": "Logic Labyrinth", "theme": "labyrinth",
        "emoji": "🌀", "boss_name": "Le Golem Infinite Loop",
        "description": "if/else, boucles, logique booléenne.",
    },
    {
        "zone_number": 3, "name": "Function Factory", "theme": "factory",
        "emoji": "⚙️", "boss_name": "L'Usine Récursive",
        "description": "Fonctions, paramètres, multi-fichiers.",
    },
    {
        "zone_number": 4, "name": "Data Fortress", "theme": "fortress",
        "emoji": "🏰", "boss_name": "La Forteresse des Données",
        "description": "Tableaux, structures, typedef.",
    },
    {
        "zone_number": 5, "name": "Pointer Abyss", "theme": "abyss",
        "emoji": "🕳️", "boss_name": "Le Dragon Segfault",
        "description": "Pointeurs, adresses, passage par référence.",
    },
    {
        "zone_number": 6, "name": "String Caverns", "theme": "cavern",
        "emoji": "🔤", "boss_name": "L'Oracle des Chaînes",
        "description": "Chaînes de caractères, fonctions string, aléatoire.",
    },
    {
        "zone_number": 7, "name": "Heap Wastes", "theme": "wasteland",
        "emoji": "☣️", "boss_name": "L'Hydre Memory Leak",
        "description": "malloc, calloc, free, fuites mémoire.",
    },
    {
        "zone_number": 8, "name": "File Sanctum", "theme": "sanctum",
        "emoji": "📜", "boss_name": "Le Gardien du Sanctuaire",
        "description": "Fichiers texte et binaires, fopen/fclose.",
    },
]
